// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvqlovrhyosyxbuvdamp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cWxvdnJoeW9zeXhidXZkYW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDQ1MTQsImV4cCI6MjA2OTM4MDUxNH0.-Kp4NikDArTuB0FJ9auFNMCJOYOqw8CfdDW-HlC7cec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});